#!/bin/sh

LIBUTILS=/usr/lib/slind-core/libutils.sh
if [ -f "$LIBUTILS" ]; then
	. $LIBUTILS
else
	echo "Error: can't load library $LIBUTILS"
	exit 1
fi

load_slind_config_common
load_slind_config_maintainer_common
load_suites_config

LIBRARY=/usr/lib/slind-core/libpoolcare.sh
if [ -f "$LIBRARY" ]; then
	. $LIBRARY
else
	echo "Error: can't load library $LIBRARY"
	exit 1
fi

DEBNAME="$1"
if [ -z "$DEBNAME" ]; then
	echo "Please specify a path to .deb file you want to inject"
	exit 1
fi

SUITE="$2"
if [ -z "$SUITE" ]; then
	echo "Please specify a suite"
	exit 1
fi

dir=`deb_cache $DEBNAME $SUITE`
if [ -z "$dir" ]; then
	yell "WARNING: package $DEBNAME does not match suite=$SUITE, ignore this package"
	exit 1
fi
echo "Moving $DEBNAME to $dir/"
mkdir -p "$dir"
mv "$DEBNAME" "$dir"
