#!/bin/sh

SUITES="clydesdale percheron attic"
DEVSUITE="clydesdale"
COMPONENTS="host-tools core gui security debug"
ARCHES="arm powerpc i386 mips mipsel sh4 uclibc-arm uclibc-powerpc uclibc-i386 uclibc-mips uclibc-mipsel uclibc-sh4"

SLIND_CONFIG=~/.slind-config
if [ -f $SLIND_CONFIG ]; then
	. $SLIND_CONFIG
else
	echo "Can't open $SLIND_CONFIG"
	exit 1
fi

if [ -z "$REPODIR" ]; then
	echo "REPODIR variable is not set in your $SLIND_CONFIG,"
	echo "please specify it to be the path to your local repository"
	exit 1
fi

LIBRARY=/usr/lib/slind-core/libpoolcare.sh
if [ -f "$LIBRARY" ]; then
	. $LIBRARY
else
	echo "Error: can't load library $LIBRARY"
	exit 1
fi

DEBNAME="$1"
if [ -z "$DEBNAME" ]; then
	echo "Please specify a path to .deb file you want to inject"
	exit 1
fi

SUITE="$2"
if [ -z "$SUITE" ]; then
	echo "Please specify a suite"
	exit 1
fi

DEBPATH_LIST=`get_deb_pathlist pool $DEBNAME $SUITE`
for dir in $DEBPATH_LIST; do
	dir="$REPODIR/$dir"
	echo "Copying to $dir"
	mkdir -p "$dir"
	cp "$DEBNAME" "$dir"
done
[ -z "$DEBPATH_LIST" ] || rm -f $DEBNAME

