#!/bin/sh

SLINDJOB_CONFIG=~/.slindjob-config
if [ ! -f "$SLINDJOB_CONFIG" ]; then
	echo -n "Configuration file $SLINDJOB_CONFIG not found, "
	echo "creating one for you"
	cp /etc/slindjob-config "$SLINDJOB_CONFIG"
fi

LOGFILE="/tmp/slindjob-`date +%C%y%m%d_%H%M`"
if [ -f "$SLINDJOB_CONFIG" ]; then
	. "$SLINDJOB_CONFIG"
else
	echo "Failed to open config file $SLINDJOB_CONFIG"
	exit 1
fi

REPORTFILE=/tmp/slindjob_maillog
if [ ! -f /usr/lib/slind-core/logging.sh ]; then
	echo "Can't open logging library"
	exit 1
else
	. /usr/lib/slind-core/logging.sh
fi

# Update all local packages' repos and build source packages
update_all()
{
	cat `find $PKGLIST_DIR -type f -name '*.pkglist'` | while read pkg; do
		echo "============================================="
		echo "# Updating local repository for $pkg"
		echo "============================================="
		logcmd "grasp update $pkg"
		echo

		echo "============================================="
		echo "# Building source package for $pkg"
		echo "============================================="
		logcmd "grasp build $pkg"
		echo
	done
}

: > "$LOGFILE"
update_all
logcmd poolcare "updating repository indices"

