#!/bin/sh


LOGFILE="/tmp/slindjob-`date +%C%y%m%d_%H%M`"
REPORTFILE=/tmp/slindjob_maillog

if [ ! -f /usr/lib/slind-core/logging.sh ]; then
	echo "Can't open logging library"
	exit 1
else
	. /usr/lib/slind-core/logging.sh
fi

LIBUTILS=/usr/lib/slind-core/libutils.sh
if [ -f "$LIBUTILS" ]; then
	. $LIBUTILS
else
	echo "Error: can't load library $LIBUTILS"
	exit 1
fi

load_slind_config_common
load_slind_config_maintainer_common
load_suites_config $SLIND_SUITE

[ -n "$HTTP_PROXY_URL" ] && PROXYENV="http_proxy=$HTTP_PROXY_URL"
[ -n "$FTP_PROXY_URL" ]  && PROXYENV="$PROXYENV ftp_proxy=$FTP_PROXY_URL"

CHROOTENV="env $PROXYENV $CHROOTENV"

CHR_PKGLIST_DIR=`conf_get_var_strict $SLIND_CONFIG slindjob chr_pkglist_dir`

# Update all local packages' repos and build source packages
update_all()
{
	cat `find $CHR_PKGLIST_DIR -type f -name '*.pkglist'` | while read pkg; do
		echo "============================================="
		echo "# Updating local repository for $pkg"
		echo "============================================="
		logcmd "grasp update $pkg"
		echo

		echo "============================================="
		echo "# Building source package for $pkg"
		echo "============================================="
		logcmd "grasp build $pkg"
		echo
	done
}

: > "$LOGFILE"
logstart "$REPORTFILE"
update_all
logcmd poolcare "updating repository indices"
# Grok new indices
$ROOT_CMD $CHROOTENV apt-get update
for ARCH in $ARCHES; do
	logcmd "$CHROOTENV mktpkg $ARCH $SLIND_SUITE" "building $ARCH cross-toolchain"
	if [ "$LASTSTATUS" = "0" ]; then
		for pkg in `ls /tmp/tpkg/*.deb`; do
			logcmd "pool-injectdeb $pkg $SLIND_SUITE" "moving `basename $pkg` to repository"
		done
	fi
done

for ARCH in $ARCHES; do
	logcmd "$CHROOTENV nc update --arch $ARCH --path $CHR_REPODIR" "updating $ARCH indices"
	if [ "$LASTSTATUS" = "0" ]; then
		cat $CHR_PKGLIST_DIR/all.pkglist | while read pkg; do
			logcmd "$CHROOTENV nc build $pkg --arch $ARCH --path $CHR_REPODIR" \
				"building $pkg for $ARCH"
		done
	fi
done
logend "$REPORTFILE"

